name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
    contents: read
    checks: write  # necesario para que dorny/test-reporter publique el check
    pull-requests: write # necesario para comentar cobertura en el PR (lo usamos más adelante)

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Cache de paquetes NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore 
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test con cobertura 
        run: >
          dotnet test --no-build --configuration Release
          --logger trx
          --results-directory ./TestResults
          --collect:"XPlat Code Coverage"

      - name: Publicar resultados de tests en el PR
        uses: dorny/test-reporter@v1  
        if: always() # siempre se ejecuta, aunque fallen los tests
        with:
          name: Resultados de Tests
          path: ./TestResults/*.trx
          reporter: dotnet-trx
      - name: Subir artifact de resultados
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/
          retention-days: 7