name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  hello-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Mostrar contexto del evento
        run: |
          echo "Evento: ${{ github.event_name }}"
          echo "Rama/ref: ${{ github.ref }}"
          echo "SHA del commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repo: ${{ github.repository }}"

      - name: Mostrar variables de entorno inyectadas por Actions
        run: env | grep GITHUB_ | sort
